"""Initial schema - all core models

Revision ID: 11492f57757d
Revises: 
Create Date: 2025-12-17 13:47:13.796923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11492f57757d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('resource_subtype', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('permanent_url', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('view_url', sa.String(), nullable=True),
    sa.Column('connected_to_app', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_attachment_gid'), 'attachment', ['gid'], unique=False)
    op.create_table('custom_field',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('representation_type', sa.String(), nullable=True),
    sa.Column('id_prefix', sa.String(), nullable=True),
    sa.Column('input_restrictions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_formula_field', sa.Boolean(), nullable=True),
    sa.Column('date_value', sa.JSON(), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.String(), nullable=True),
    sa.Column('display_value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('custom_label', sa.String(), nullable=True),
    sa.Column('custom_label_position', sa.String(), nullable=True),
    sa.Column('is_global_to_workspace', sa.Boolean(), nullable=True),
    sa.Column('has_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('asana_created_field', sa.String(), nullable=True),
    sa.Column('is_value_read_only', sa.Boolean(), nullable=True),
    sa.Column('privacy_setting', sa.String(), nullable=True),
    sa.Column('default_access_level', sa.String(), nullable=True),
    sa.Column('resource_subtype', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_custom_field_gid'), 'custom_field', ['gid'], unique=False)
    op.create_table('project',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('default_view', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('html_notes', sa.String(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('privacy_setting', sa.String(), nullable=True),
    sa.Column('start_on', sa.Date(), nullable=True),
    sa.Column('default_access_level', sa.String(), nullable=True),
    sa.Column('minimum_access_level_for_customization', sa.String(), nullable=True),
    sa.Column('minimum_access_level_for_sharing', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permalink_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_project_gid'), 'project', ['gid'], unique=False)
    op.create_table('section',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_section_gid'), 'section', ['gid'], unique=False)
    op.create_table('story',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resource_subtype', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('html_text', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('sticker_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('hearted', sa.Boolean(), nullable=True),
    sa.Column('num_hearts', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.Column('old_name', sa.String(), nullable=True),
    sa.Column('new_name', sa.String(), nullable=True),
    sa.Column('old_resource_subtype', sa.String(), nullable=True),
    sa.Column('new_resource_subtype', sa.String(), nullable=True),
    sa.Column('old_text_value', sa.String(), nullable=True),
    sa.Column('new_text_value', sa.String(), nullable=True),
    sa.Column('old_number_value', sa.Integer(), nullable=True),
    sa.Column('new_number_value', sa.Integer(), nullable=True),
    sa.Column('new_approval_status', sa.String(), nullable=True),
    sa.Column('old_approval_status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_story_gid'), 'story', ['gid'], unique=False)
    op.create_table('tag',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('permalink_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_tag_gid'), 'tag', ['gid'], unique=False)
    op.create_table('task',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('resource_subtype', sa.String(), nullable=True),
    sa.Column('created_by', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('assignee_status', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('external', sa.JSON(), nullable=True),
    sa.Column('html_notes', sa.String(), nullable=True),
    sa.Column('hearted', sa.Boolean(), nullable=True),
    sa.Column('is_rendered_as_separator', sa.Boolean(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('memberships', sa.JSON(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('num_hearts', sa.Integer(), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.Column('num_subtasks', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_on', sa.Date(), nullable=True),
    sa.Column('actual_time_minutes', sa.Float(), nullable=True),
    sa.Column('permalink_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_task_gid'), 'task', ['gid'], unique=False)
    op.create_table('team',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('html_description', sa.String(), nullable=True),
    sa.Column('permalink_url', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('edit_team_name_or_description_access_level', sa.String(), nullable=True),
    sa.Column('edit_team_visibility_or_trash_team_access_level', sa.String(), nullable=True),
    sa.Column('member_invite_management_access_level', sa.String(), nullable=True),
    sa.Column('guest_invite_management_access_level', sa.String(), nullable=True),
    sa.Column('join_request_management_access_level', sa.String(), nullable=True),
    sa.Column('team_member_removal_access_level', sa.String(), nullable=True),
    sa.Column('team_content_management_access_level', sa.String(), nullable=True),
    sa.Column('endorsed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_team_gid'), 'team', ['gid'], unique=False)
    op.create_table('user',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('photo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_user_gid'), 'user', ['gid'], unique=False)
    op.create_table('webhook',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_content', sa.String(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_retry_count', sa.Integer(), nullable=True),
    sa.Column('next_attempt_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_deletion_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filters', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_webhook_gid'), 'webhook', ['gid'], unique=False)
    op.create_table('workspace',
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email_domains', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_organization', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_workspace_gid'), 'workspace', ['gid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_gid'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_webhook_gid'), table_name='webhook')
    op.drop_table('webhook')
    op.drop_index(op.f('ix_user_gid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_team_gid'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_task_gid'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_tag_gid'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_story_gid'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_section_gid'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_project_gid'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_custom_field_gid'), table_name='custom_field')
    op.drop_table('custom_field')
    op.drop_index(op.f('ix_attachment_gid'), table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
