"""add_custom_id_to_task

Revision ID: 44a99a0ba7dc
Revises: 11492f57757d
Create Date: 2025-12-17 17:24:43.172362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a99a0ba7dc'
down_revision: Union[str, Sequence[str], None] = '11492f57757d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('custom_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_task_custom_id'), 'task', ['custom_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_custom_id'), table_name='task')
    op.drop_column('task', 'custom_id')
    # ### end Alembic commands ###
